Add treble_up, treble_down, bass_up, bass_down
ol-iver/denonavr pull request #193
Opened 2021-02-13 09:46 UTC by MarBra

I have added treble_up, treble_down, bass_up, bass_down and a update_tonecontrol method.

2021-03-14 20:41 UTC, scarface-4711 requested changes
Thanks @MarBra 
There is just a little remark about running updates after up/down commands.

2021-03-14 20:41 UTC, scarface-4711 commented on denonavr/tonecontrol.py
> +
How about an `await self.async_update()` at this place?
Otherwise the command will work only once.

2021-03-14 20:41 UTC, scarface-4711 commented on denonavr/tonecontrol.py
> +
same here with `await self.async_update()`

2021-03-14 20:41 UTC, scarface-4711 commented on denonavr/tonecontrol.py
> +
same here with `await self.async_update()`

2021-03-14 20:41 UTC, scarface-4711 commented on denonavr/tonecontrol.py
> +
same here with `await self.async_update()`

2021-03-16 13:56 UTC, MarBra commented
> Thanks @MarBra
> There is just a little remark about running updates after up/down commands.

Thanks for the review @scarface-4711 
I have added the update call to the generic set command. Is this OK for you or shall I add it to the methods itself?

2021-03-21 09:37 UTC, scarface-4711 commented
> 
> 
> > Thanks @MarBra
> > There is just a little remark about running updates after up/down commands.
> 
> Thanks for the review @scarface-4711
> I have added the update call to the generic set command. Is this OK for you or shall I add it to the methods itself?

@MarBra I would prefer it just in the up/down methods themselves, that the update method is just called when it is absolutely neccessary. This follows the way the other interfaces are designed.

2021-03-21 09:42 UTC, MarBra commented
> > > Thanks @MarBra
> > > There is just a little remark about running updates after up/down commands.
> > 
> > 
> > Thanks for the review @scarface-4711
> > I have added the update call to the generic set command. Is this OK for you or shall I add it to the methods itself?
> 
> @MarBra I would prefer it just in the up/down methods themselves, that the update method is just called when it is absolutely neccessary. This follows the way the other interfaces are designed.

Alright 👍 Just pushed a new commit.

2021-03-21 11:34 UTC, scarface-4711 approved these changes

2021-03-21 11:35 UTC, scarface-4711 commented
thank you 😄

2021-03-21 11:35 UTC, merged